version: '3.8'
services:
  backend:
    build: ./server
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

  frontend:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:9000
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
